<a href="https://colab.research.google.com/github/pillasandeep/FML/blob/main/logistic_regression_loan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
df=pd.read_csv("Loan Prediction Dataset.csv")
df

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0   
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Urban           Y  
1               1.0         Rural           N  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
..              ...           ...         ...  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N  

[614 rows x 13 columns]

In [ ]:
df=df.drop(columns="Dependents")


Loan_ID  Gender Married     Education Self_Employed  ApplicantIncome  \
0    LP001002    Male      No      Graduate            No             5849   
1    LP001003    Male     Yes      Graduate            No             4583   
2    LP001005    Male     Yes      Graduate           Yes             3000   
3    LP001006    Male     Yes  Not Graduate            No             2583   
4    LP001008    Male      No      Graduate            No             6000   
..        ...     ...     ...           ...           ...              ...   
609  LP002978  Female      No      Graduate            No             2900   
610  LP002979    Male     Yes      Graduate            No             4106   
611  LP002983    Male     Yes      Graduate            No             8072   
612  LP002984    Male     Yes      Graduate            No             7583   
613  LP002990  Female      No      Graduate           Yes             4583   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                  0.0         NaN             360.0             1.0   
1               1508.0       128.0             360.0             1.0   
2                  0.0        66.0             360.0             1.0   
3               2358.0       120.0             360.0             1.0   
4                  0.0       141.0             360.0             1.0   
..                 ...         ...               ...             ...   
609                0.0        71.0             360.0             1.0   
610                0.0        40.0             180.0             1.0   
611              240.0       253.0             360.0             1.0   
612                0.0       187.0             360.0             1.0   
613                0.0       133.0             360.0             0.0   

    Property_Area Loan_Status  
0           Urban           Y  
1           Rural           N  
2           Urban           Y  
3           Urban           Y  
4           Urban           Y  
..            ...         ...  
609         Rural           Y  
610         Rural           Y  
611         Urban           Y  
612         Urban           Y  
613     Semiurban           N  

[614 rows x 12 columns]

In [ ]:
df['Loan_ID'] = df['Loan_ID'].astype('category')
df['Loan_ID'] = df['Loan_ID'].cat.codes
df['Gender'] = df['Gender'].astype('category')
df['Gender'] = df['Gender'].cat.codes
df['Married'] = df['Married'].astype('category')
df['Married'] = df['Married'].cat.codes
df['Education'] = df['Education'].astype('category')
df['Education'] = df['Education'].cat.codes
df['Self_Employed'] = df['Self_Employed'].astype('category')
df['Self_Employed'] = df['Self_Employed'].cat.codes
df['Loan_Status'] = df['Loan_Status'].astype('category')
df['Loan_Status'] = df['Loan_Status'].cat.codes
df['Property_Area'] = df['Property_Area'].astype('category')
df['Property_Area'] = df['Property_Area'].cat.codes
df

In [ ]:
df.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [ ]:
df=df.dropna()
df

Loan_ID  Gender  Married  Education  Self_Employed  ApplicantIncome  \
1          0       1        1          0              0             4583   
2          1       1        1          0              1             3000   
3          2       1        1          1              0             2583   
4          3       1        0          0              0             6000   
5          4       1        1          0              1             5417   
..       ...     ...      ...        ...            ...              ...   
609      485       0        0          0              0             2900   
610      486       1        1          0              0             4106   
611      487       1        1          0              0             8072   
612      488       1        1          0              0             7583   
613      489       0        0          0              1             4583   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
1               1508.0       128.0             360.0             1.0   
2                  0.0        66.0             360.0             1.0   
3               2358.0       120.0             360.0             1.0   
4                  0.0       141.0             360.0             1.0   
5               4196.0       267.0             360.0             1.0   
..                 ...         ...               ...             ...   
609                0.0        71.0             360.0             1.0   
610                0.0        40.0             180.0             1.0   
611              240.0       253.0             360.0             1.0   
612                0.0       187.0             360.0             1.0   
613                0.0       133.0             360.0             0.0   

     Property_Area  Loan_Status  
1                0            0  
2                2            1  
3                2            1  
4                2            1  
5                2            1  
..             ...          ...  
609              0            1  
610              0            1  
611              2            1  
612              2            1  
613              1            0  

[490 rows x 12 columns]

In [ ]:
X=df.drop(columns='Loan_Status')
X

Loan_ID  Gender  Married  Education  Self_Employed  ApplicantIncome  \
1          0       1        1          0              0             4583   
2          1       1        1          0              1             3000   
3          2       1        1          1              0             2583   
4          3       1        0          0              0             6000   
5          4       1        1          0              1             5417   
..       ...     ...      ...        ...            ...              ...   
609      485       0        0          0              0             2900   
610      486       1        1          0              0             4106   
611      487       1        1          0              0             8072   
612      488       1        1          0              0             7583   
613      489       0        0          0              1             4583   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
1               1508.0       128.0             360.0             1.0   
2                  0.0        66.0             360.0             1.0   
3               2358.0       120.0             360.0             1.0   
4                  0.0       141.0             360.0             1.0   
5               4196.0       267.0             360.0             1.0   
..                 ...         ...               ...             ...   
609                0.0        71.0             360.0             1.0   
610                0.0        40.0             180.0             1.0   
611              240.0       253.0             360.0             1.0   
612                0.0       187.0             360.0             1.0   
613                0.0       133.0             360.0             0.0   

     Property_Area  
1                0  
2                2  
3                2  
4                2  
5                2  
..             ...  
609              0  
610              0  
611              2  
612              2  
613              1  

[490 rows x 11 columns]

In [ ]:
y=df['Loan_Status']
y

1      0
2      1
3      1
4      1
5      1
      ..
609    1
610    1
611    1
612    1
613    0
Name: Loan_Status, Length: 490, dtype: int8

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=21)

In [ ]:
X_train

Loan_ID  Gender  Married  Education  Self_Employed  ApplicantIncome  \
553      439       1        1          1              0             2454   
55        42       1        1          0              0             2708   
174      135       1        1          1              1             4344   
384      305       1        1          0              0             4566   
419      335       1        1          0              0             3246   
..       ...     ...      ...        ...            ...              ...   
61        48       1        1          0              0             3029   
327      260       1        1          0              1             5818   
394      312       1        1          0              0             3100   
262      207       0        0          0              0             3481   
573      457       1        1          1              0             6125   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
553             2333.0       181.0             360.0             0.0   
55              1167.0        97.0             360.0             1.0   
174              736.0        87.0             360.0             1.0   
384                0.0       100.0             360.0             1.0   
419             1417.0       138.0             360.0             1.0   
..                 ...         ...               ...             ...   
61                 0.0        99.0             360.0             1.0   
327             2160.0       184.0             360.0             1.0   
394             1400.0       113.0             360.0             1.0   
262                0.0       155.0              36.0             1.0   
573             1625.0       187.0             480.0             1.0   

     Property_Area  
553              2  
55               1  
174              1  
384              2  
419              1  
..             ...  
61               2  
327              1  
394              2  
262              1  
573              1  

[343 rows x 11 columns]

In [ ]:
X_test

Loan_ID  Gender  Married  Education  Self_Employed  ApplicantIncome  \
33        25       1        1          0              0             3500   
225      177       1        1          0              0             3250   
269      213       0        0          0              0             2876   
425      339       1        1          0              0             2666   
66        52       1        0          1              0             3200   
..       ...     ...      ...        ...            ...              ...   
191      149       1        0          0              0            12000   
303      244       1        1          0              0             1625   
17        14       0        0          0              0             3510   
563      448       1        0          1              1             5800   
594      473       1        1          0              1            16120   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
33              1667.0       114.0             360.0             1.0   
225                0.0       170.0             360.0             1.0   
269             1560.0        90.0             360.0             1.0   
425             4300.0       121.0             360.0             1.0   
66              2254.0       126.0             180.0             0.0   
..                 ...         ...               ...             ...   
191                0.0       164.0             360.0             1.0   
303             1803.0        96.0             360.0             1.0   
17                 0.0        76.0             360.0             0.0   
563                0.0       132.0             360.0             1.0   
594                0.0       260.0             360.0             1.0   

     Property_Area  
33               1  
225              0  
269              2  
425              0  
66               2  
..             ...  
191              1  
303              2  
17               2  
563              1  
594              2  

[147 rows x 11 columns]

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

In [ ]:
X_test_scaled = scaler.fit_transform(X_test)

In [ ]:
X_train_scaled

array([[ 1.35401225,  0.4650936 ,  0.73356431, ...,  0.26155312,
        -2.33916611,  1.27197662],
       [-1.47594236,  0.4650936 ,  0.73356431, ...,  0.26155312,
         0.42750277,  0.        ],
       [-0.81300588,  0.4650936 ,  0.73356431, ...,  0.26155312,
         0.42750277,  0.        ],
       ...,
       [ 0.44871191,  0.4650936 ,  0.73356431, ...,  0.26155312,
         0.42750277,  1.27197662],
       [-0.29976475, -2.15010484, -1.363207  , ..., -4.85946898,
         0.42750277,  0.        ],
       [ 1.48232254,  0.4650936 ,  0.73356431, ...,  2.15822797,
         0.42750277,  0.        ]])

In [ ]:
X_test_scaled

array([[-1.4548496 ,  0.47434165,  0.750886  , ...,  0.2935846 ,
         0.41952354, -0.12700013],
       [-0.3961569 ,  0.47434165,  0.750886  , ...,  0.2935846 ,
         0.41952354, -1.46050146],
       [-0.14541389, -2.10818511, -1.33176008, ...,  0.2935846 ,
         0.41952354,  1.20650121],
       ...,
       [-1.53146552, -2.10818511, -1.33176008, ...,  0.2935846 ,
        -2.38365647,  1.20650121],
       [ 1.49138075,  0.47434165, -1.33176008, ...,  0.2935846 ,
         0.41952354, -0.12700013],
       [ 1.66550784,  0.47434165,  0.750886  , ...,  0.2935846 ,
         0.41952354,  1.20650121]])

In [ ]:
model = LogisticRegression(random_state = 0).fit(X_train_scaled,y_train)

In [ ]:
model.predict(X_train_scaled)

array([0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [ ]:
X_test = scaler.transform(X_test)
y_pred = model.predict(X_test)

In [ ]:
model.score(X_test, y_test)

0.7891156462585034

In [ ]:
confusion_matrix(y_test, y_pred)

array([[20, 29],
       [ 2, 96]])

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.91      0.41      0.56        49
           1       0.77      0.98      0.86        98

    accuracy                           0.79       147
   macro avg       0.84      0.69      0.71       147
weighted avg       0.82      0.79      0.76       147

