<a href="https://colab.research.google.com/github/pillasandeep/FML/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [ ]:
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr2=np.zeros((3,3))
arr2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr3=np.full((2,2),99)
arr3


array([[99, 99],
       [99, 99]])

In [ ]:
arr3.shape


(2, 2)

In [ ]:
arr3[0,1]

99

In [ ]:
arr3[0][-1]

99

In [ ]:
arr3[0][0]=997
print(arr3)


[[997  99]
 [ 99  99]]


In [ ]:
print(arr1[1,-2])

5
